FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm rebuild --auto-approve-builds
RUN pnpm prisma generate --auto-approve-builds

ENV NEXT_TELEMETRY_DISABLED=1

# Hanya variabel NEXT_PUBLIC_* yang perlu di-embed saat build
ARG NEXT_PUBLIC_SCHOOL_NPSN
ARG NEXT_PUBLIC_SCHOOL_CONTACT_ADDRESS
ARG NEXT_PUBLIC_SCHOOL_CONTACT_EMAIL
ARG NEXT_PUBLIC_SCHOOL_CONTACT_PHONE
ARG NEXT_PUBLIC_SCHOOL_CONTACT_MAP
ENV NEXT_PUBLIC_SCHOOL_NPSN=$NEXT_PUBLIC_SCHOOL_NPSN
ENV NEXT_PUBLIC_SCHOOL_CONTACT_ADDRESS=$NEXT_PUBLIC_SCHOOL_CONTACT_ADDRESS
ENV NEXT_PUBLIC_SCHOOL_CONTACT_EMAIL=$NEXT_PUBLIC_SCHOOL_CONTACT_EMAIL
ENV NEXT_PUBLIC_SCHOOL_CONTACT_PHONE=$NEXT_PUBLIC_SCHOOL_CONTACT_PHONE
ENV NEXT_PUBLIC_SCHOOL_CONTACT_MAP=$NEXT_PUBLIC_SCHOOL_CONTACT_MAP

RUN pnpm run build